# list of packages/ libraries used for the PyVis workshop
# use 'conda env create -f environment.yml'
# to create the environment

name: pyvis

channels:
    - conda-forge

dependencies:
    - python=3.8
    - jupyterlab
    - matplotlib
    - numpy
    - netCDF4
    - pandas
    - seaborn
    - cartopy
    - xarray
    - pip
    - scipy
    - geopandas
    - ipympl
    - black
    - isort
    - jupyterlab_code_formatter
    - cmcrameri
    - ipython
    - psy-maps
    - pip:
        - https://github.com/mathause/mplotutils/archive/v0.2.0.zip
        - git+https://github.com/C2SM/iconarray@v0.1.19#egg=iconarray
