# list of packages/ libraries used for the PyVis workshop
# use 'conda env create -f environment.yml'
# to create the environment

name: pyvis

channels:
    - conda-forge

dependencies:
    - python=3.8
    - jupyterlab
    - matplotlib
    - numpy
    - netCDF4
    - pandas
    - seaborn
    - cartopy
    - xarray
    - pip
    - scipy
    - geopandas
    - ipympl
    - black
    - isort
    - ipykernel
    - jupyterlab_code_formatter
    - pip:
        - https://github.com/mathause/mplotutils

